#15 add create user sequence diagram
orion-services/users pull request #23
Opened 2021-07-25 20:15 UTC by GiovaniBoff

![image](https://user-images.githubusercontent.com/42684243/126912117-a5440e77-0cfb-4b29-85cb-c7f1a4cab378.png)

closes #15

2021-07-25 21:33 UTC, nikolasFreitas commented
- Review use of alternatives in plant UML. You should use it to maintain a clear flow of sequence subtypes.
- The arrows must be what you are requesting to the next service.
- The returning must be direct, without details.
- When the service have some process that you think it's important to diagram, uses an arrow pointing to the same service. Ex: `User -> User: validate X`
- Avoid show implementations like "valid request body" or methods name. The diagram must show just the data flow of microsservices, not depending of implementation or architecture. Think it like the rest, this is documented agnostic of programming language or architecture.

**Rember to update the imagem with the changes in your diagram during code review.**

2021-07-28 00:59 UTC, lucasTovo submitted a review, later dismissed
Remove BFF from protected container please.

2021-07-31 22:48 UTC, nikolasFreitas requested changes

2021-07-31 22:48 UTC, nikolasFreitas commented on docs/sequences-diagrams/create-user.wsd
> +        User -> User: "Verify user data"
I think you can remove the step 6 because you're verifying something that the service persisted in DB.

2021-08-01 17:45 UTC, merged