#18 add authenticate user sequence diagram
orion-services/users pull request #24
Opened 2021-07-31 22:23 UTC by GiovaniBoff

Closes #18 

![hLJDZXCn3BxtAQnmuDGNM26qfMXF7D3-Y0Fqa2Q6YJfDYkCi2q-FnwtP3an7GjevJ5Bt-_difBskx8dRlb-0FBvnoMs_HGBzp8bx1BTgt67c53mZj8e45Rytp07TuiWBN0ZMVHAK5WwU19uEFZEykxdHshOyWVj8XJ4mHX3Zi7FmwaFwrl7wfy__41_4IOkOuy3MVVJijxuYl3zjjAgle](https://user-images.githubusercontent.com/42684243/127753726-94ef85db-6dfb-4065-8bb3-e9e3ee0a26e3.png)

2021-08-02 04:10 UTC, nikolasFreitas requested changes

2021-08-02 04:10 UTC, nikolasFreitas commented on docs/autheticate-user.wsd
> +    alt "User with token expired"
Is that an alternative? For me it looks like this is the normal flow.

2021-08-03 01:36 UTC, evandroLutz requested changes
review the chain of alternatives. user with expired token is an error case, so it should come second, as an alternative to success case.

2021-08-09 17:13 UTC, nikolasFreitas requested changes

2021-08-09 17:13 UTC, nikolasFreitas commented on docs/autheticate-user.wsd
> +    user -> db: Validate credentials
The database doesn't validate anything. It just save the user data. The system must validate if the database find the user data. Think the flow of how the login works.

2021-08-10 00:25 UTC, merged