#19 add refresh token sequence diagram
orion-services/users pull request #27
Opened 2021-08-01 18:35 UTC by GiovaniBoff

Closes #19 
![image](https://user-images.githubusercontent.com/42684243/127781701-0539a9c9-0a0f-4f2e-8676-2a800d5ec695.png)

2021-08-01 22:02 UTC, nikolasFreitas requested changes

2021-08-01 22:02 UTC, nikolasFreitas commented on docs/refresh-token.wsd
> +    user-> db: "Search  refresh token"
"Search refresh token" is what? Does it should be an old token instead of "refresh token"? I mean, exist just two tokens: the new token and the old token, do you agree?

2021-08-01 22:17 UTC, nikolasFreitas requested changes

2021-08-01 22:17 UTC, nikolasFreitas commented on docs/refresh-token.wsd
> +            user --> bff: "Authorized [New Access & Refresh token]"
I would remove this "**Authorized**" and make it more clear what is going on.

2021-08-02 01:57 UTC, evandroLutz requested changes
could change the name of the authorization type to better differentiate the new access and refresh token from the other authorization type

2021-08-07 01:14 UTC, nikolasFreitas requested changes

2021-08-07 01:14 UTC, nikolasFreitas commented on docs/refresh-token.wsd
> +    actor client as "User Logged"
I think you could change it for two lines like "User Logged \ \n Service Logged"

2021-08-07 01:14 UTC, nikolasFreitas commented on docs/refresh-token.wsd
> +        user --> bff: "Authorized [New Access Token]"
Should be access token & refresh token, right?

2021-08-07 01:59 UTC, nikolasFreitas requested changes

2021-08-07 01:59 UTC, nikolasFreitas commented on docs/refresh-token.wsd
> +        else Refresh token is expired
If the refresh token is not Ok, should just return an error. Do not generate an valid token to an expired refresh token.

2021-08-10 00:26 UTC, merged