#20 add register new external service sequence diagram
orion-services/users pull request #28
Opened 2021-08-01 19:48 UTC by GiovaniBoff

Closes #20 

![image](https://user-images.githubusercontent.com/42684243/127783492-155b84cb-21af-49c2-8d90-6792758eb8a9.png)

2021-08-01 21:41 UTC, nikolasFreitas requested changes
Gio, could you be more specific on what type of error this could do, eg. more than one key for the same service or service already registered

2021-08-02 00:06 UTC, evandroLutz requested changes
I believe it would be valid to register the registration attempt process also in case of error, but returning an error when trying to register the service

2021-08-09 17:27 UTC, nikolasFreitas requested changes

2021-08-09 17:27 UTC, nikolasFreitas commented on docs/register-external-service.wsd
> +        user -> user: Generate credentials (JWT)\n [Access & Refresh]
the service must not generate the JWT on new service registration. The token is generated only after service login.

2021-08-09 17:27 UTC, nikolasFreitas commented on docs/register-external-service.wsd
> +@startuml
I think the User service must generate the credentials (account and password) for the external user. 
So the flow is: Admin register new service -> User service generate credentials -> Persist those and the service data into DB -> Return credentials with encrypted.

2021-08-10 01:43 UTC, merged